In [1]:
# The %... is an iPython thing, and is not part of the Python language.
# In this case we're just telling the plotting library to draw things on
# the notebook, instead of on a separate window.
%matplotlib inline 
#this line above prepares IPython notebook for working with matplotlib

# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().

import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm #allows us easy access to colormaps
import matplotlib.pyplot as plt #sets up plotting under plt
import pandas as pd #lets us handle data as dataframes
#sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns #sets up styles and gives us more plotting options

In [2]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run
    
Returns
-------
sims : array
    Random array of 0s, 1s and 2s
    
Example
-------
>>> print simulate_prizedoor(3)
array([0,0,2])
"""

def simulate_prizedoor(nsim):
    return np.random.randint(0,3,(nsim))

In [3]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for
    
Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1 or 2
    
Example
-------

>>> print simulate_guess(5)
array([0,0,0,0,0])
"""

def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int)

In [4]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestant's guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    The door that the contestant guessed in each simulation
    
Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses
    
Examples
--------
>>> print goat_door(np.array([0,1,2]), np.array([1,1,1]))
>>> array([2,2,0])
"""

def goat_door(prizedoors, guesses):
    
    #strategy: generate random answers, and
    #keep updating until they satisfy the rule
    #that they aren't a prizedoor or a guess
    result = np.random.randint(0,3,prizedoors.size)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        if not bad.any()
            return result
        result[bad] = np.random.randint(0,3,bad.sum())

SyntaxError: invalid syntax (<ipython-input-4-29efff2234eb>, line 36)

In [5]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestant's guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    The door that the contestant guessed in each simulation
    
Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses
    
Examples
--------
>>> print goat_door(np.array([0,1,2]), np.array([1,1,1]))
>>> array([2,2,0])
"""

def goat_door(prizedoors, guesses):
    
    #strategy: generate random answers, and
    #keep updating until they satisfy the rule
    #that they aren't a prizedoor or a guess
    result = np.random.randint(0,3,prizedoors.size)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        if not bad.any():
            return result
        result[bad] = np.random.randint(0,3,bad.sum())

In [6]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
    Array of original guesses, for each simulation
goatdoors : array
    Array of revealed goat doors for each simulation
    
Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0,1,2]), np.array([1,2,1]))
>>> array([2,0,0])
"""

def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0,1):2,(0,2):1,(1,0):2,(1,2):0,(2,0):1,(2,1):0}
    for i in [0 1 2]:
        for j in [0 1 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i,j)], result)
    return result

SyntaxError: invalid syntax (<ipython-input-6-abad61096dd0>, line 28)

In [7]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
    Array of original guesses, for each simulation
goatdoors : array
    Array of revealed goat doors for each simulation
    
Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0,1,2]), np.array([1,2,1]))
>>> array([2,0,0])
"""

def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0,1):2,(0,2):1,(1,0):2,(1,2):0,(2,0):1,(2,1):0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i,j)], result)
    return result

In [8]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation
    
Returns
-------
percentage : number between 0 and 100
    The win percentage
    
Examples
--------
>>> print win_percentage(np.array([0,1,2]), np.array([0,0,0]))
>>> 33.333
"""

def win_percentage(guesses, prizedoors):
    return 100 * (guesses == prizedoors).mean()

In [9]:
nsim = 10000

# keep guesses
print "Win percentage when keeping original door"
print win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim))

# switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd,guess)
guess = switch_guess(guess, goats)
print "Win percentage when switching doors"
print win_percentage(pd, guess).mean()

Win percentage when keeping original door
33.57
Win percentage when switching doors
66.32
